# Generated by Django 4.0.1 on 2022-01-15 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('H', 'House'), ('AP', 'Apartment / Flat'), ('TH', 'Townhouse'), ('P', 'Vacant Land / Plot'), ('F', 'Farm'), ('C', 'Commercial Property'), ('I', 'Industrial Property')], default='H', max_length=2)),
                ('property_status', models.CharField(choices=[('S', 'For Sale'), ('R', 'To Rent'), ('F', 'Forclosure'), ('A', 'Auction')], default='S', max_length=2)),
                ('price', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
