# Generated by Django 4.0.1 on 2022-01-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.SmallIntegerField(null=True),
        ),
    ]
