# Generated by Django 4.0.1 on 2022-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_levies_property_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='baths',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='beds',
            new_name='bedrooms',
        ),
        migrations.AddField(
            model_name='property',
            name='is_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
