# Generated by Django 4.0.1 on 2022-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_baths_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('FS', 'Free State'), ('G', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('MPG', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('EC', 'Eastern Cape'), ('WC', 'Western Cape')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Levies',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='erf_size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('S', 'For Sale'), ('R', 'To Rent'), ('F', 'Forclosure'), ('A', 'Auction')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('H', 'House'), ('AP', 'Apartment / Flat'), ('TH', 'Townhouse'), ('P', 'Vacant Land / Plot'), ('F', 'Farm'), ('C', 'Commercial Property'), ('I', 'Industrial Property')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rates_and_taxes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
