# Generated by Django 4.0.1 on 2022-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_city_property_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='suburb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='erf_size',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_size',
            field=models.SmallIntegerField(null=True),
        ),
    ]
