# Generated by Django 4.0.1 on 2022-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.UUIDField>/images'),
        ),
    ]
