# Generated by Django 4.0.1 on 2022-01-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_images_propertyimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('primary_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.DeleteModel(
            name='PropertyImages',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
