# Generated by Django 4.0.1 on 2022-01-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyimage_remove_property_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='primary_image',
            new_name='is_primary',
        ),
    ]
