# Generated by Django 4.0.1 on 2022-01-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_rename_primary_image_propertyimage_is_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='image',
            new_name='images',
        ),
    ]
