# Generated by Django 4.0.1 on 2022-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_propertyimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
