# Generated by Django 4.0.1 on 2022-01-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_propertyimage_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='has_garden',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_pet_friendly',
        ),
        migrations.CreateModel(
            name='PropertyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pet_friendly', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
        ),
    ]
