# Generated by Django 4.0.1 on 2022-01-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_rename_property_propertyfeatures_prop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyFeatures',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(to='properties.Features', verbose_name='features'),
        ),
    ]
