# Generated by Django 4.0.1 on 2022-01-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_features_delete_propertyfeatures_property_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='PropertyFeature',
        ),
    ]
