# Generated by Django 4.0.1 on 2022-01-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_remove_property_features_propertyfeature_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfeature',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(to='properties.PropertyFeature', verbose_name='features'),
        ),
    ]
