# Generated by Django 4.0.1 on 2022-01-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_remove_propertyfeature_property_property_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Levies',
            new_name='levies',
        ),
    ]
