# Generated by Django 4.0.1 on 2022-01-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_alter_property_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('None', 'Property Status'), ('H', 'House'), ('AP', 'Apartment / Flat'), ('TH', 'Townhouse'), ('P', 'Vacant Land / Plot'), ('F', 'Farm'), ('C', 'Commercial Property'), ('I', 'Industrial Property')], max_length=4, null=True),
        ),
    ]
