# Generated by Django 4.0.1 on 2022-01-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('ANY', 'ANY'), ('S', 'For Sale'), ('R', 'To Rent'), ('F', 'Forclosure'), ('A', 'Auction')], default='ANY', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('ANY', 'ANY'), ('H', 'House'), ('AP', 'Apartment / Flat'), ('TH', 'Townhouse'), ('P', 'Vacant Land / Plot'), ('F', 'Farm'), ('C', 'Commercial Property'), ('I', 'Industrial Property')], default='ANY', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('ANY', 'ANY'), ('FS', 'Free State'), ('G', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('MPG', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('EC', 'Eastern Cape'), ('WC', 'Western Cape')], default='ANY', max_length=4, null=True),
        ),
    ]
